#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

if [ -n "$STAGED_GO_FILES" ]; then
  echo "$STAGED_GO_FILES" | xargs go tool gofumpt -w
  echo "$STAGED_GO_FILES" | xargs go tool golines -w
  echo "$STAGED_GO_FILES" | xargs git add
fi

go test ./test/
