#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

if [ -n "$STAGED_GO_FILES" ]; then
  echo "Formatting staged Go files..."
  echo "$STAGED_GO_FILES" | xargs $HOME/go/bin/gofumpt -l -w
  echo "$STAGED_GO_FILES" | xargs $HOME/go/bin/golines -l -w
  echo "$STAGED_GO_FILES" | xargs git add
  echo "Formatting complete!"
fi

go test ./test/
